# Generated by Django 5.1.2 on 2024-10-11 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_outlineserver_description_alter_city_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=10000, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=1500, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=1500, verbose_name='last name')),
                ('subscription_expire_datetime', models.DateTimeField(blank=True, null=True)),
                ('subscription_price', models.DecimalField(decimal_places=2, default=1000, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outline_server_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osk_telegram_user', related_query_name='osk_telegram_user', to='servers.outlineserverkey')),
            ],
        ),
    ]
