# Generated by Django 5.1.2 on 2024-10-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
