# Generated by Django 5.1.2 on 2024-10-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramuser_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='last_bot_message_id',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
