# Generated by Django 5.1.2 on 2024-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramuser_last_bot_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(max_length=10000, null=True, verbose_name='username'),
        ),
    ]
