# Generated by Django 5.1.2 on 2024-10-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_bot_message_id',
        ),
    ]
