# Generated by Django 5.1.2 on 2024-10-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_telegramuser_last_bot_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='username'),
        ),
    ]
