# Generated by Django 5.1.2 on 2024-10-11 00:56

import core.utils.nanoid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlineserver',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.CharField(default=core.utils.nanoid.generate_nanoid_32, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(default=core.utils.nanoid.generate_nanoid_32, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='outlineserver',
            name='id',
            field=models.CharField(default=core.utils.nanoid.generate_nanoid_32, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='OutlineServerKey',
            fields=[
                ('id', models.CharField(default=core.utils.nanoid.generate_nanoid_32, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('external_id', models.CharField(max_length=10000)),
                ('access_key', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servers.outlineserver')),
            ],
            options={
                'db_table': 'outline_server_keys',
            },
        ),
    ]
