# Generated by Django 5.1.2 on 2024-10-11 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_outlineserver_description_alter_city_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='emoji',
            field=models.CharField(default='🏳', max_length=255),
        ),
        migrations.AlterField(
            model_name='outlineserver',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_outline_servers', related_query_name='city_outline_servers', to='servers.city'),
        ),
    ]
