# Generated by Django 5.1.2 on 2024-10-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_remove_city_code_remove_country_code_country_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlineserver',
            name='host',
            field=models.CharField(default='None', max_length=10000),
        ),
        migrations.AddField(
            model_name='outlineserver',
            name='port',
            field=models.CharField(default='None', max_length=10000),
        ),
        migrations.AddField(
            model_name='outlineserverkey',
            name='method',
            field=models.CharField(default='None', max_length=10000),
        ),
        migrations.AddField(
            model_name='outlineserverkey',
            name='password',
            field=models.CharField(default='None', max_length=10000),
        ),
    ]
